Variable definitions moved to the start of scopes, fixed indentation,…
Samaspp/todolist pull request #14
Opened 2023-10-04 12:33 UTC by Samaspp

… removed comments,logs

2023-10-05 09:02 UTC, pjoshk requested changes

2023-10-05 09:02 UTC, pjoshk commented on script.js
> +    img.src = 'images/icons8-edit-50.png'
This path is used multiple times in the file. If the name/location of the file changes, it will be error prone to change everywhere manually. Hence this is a great candidate for a constant. Changing it at one place will update it everywhere.

Define text constants in the start of the file, (ideally in a separate file but maybe later) like this
const IMG_SRC = "images/icons8-edit-50.png";

note that the variable is in all caps, showing it's a text/number constant

2023-10-05 09:02 UTC, pjoshk commented on script.js
> +    img.src = 'images/icons8-edit-50.png'
you could have two variables like this
EDIT_IMG_NAME = "icons8-edit-50.png";
EDIT_IMG_PATH = `images/${EDIT_IMAGE_NAME}`;

- notice the use of descriptive name so we know which image we are talking about.
- notice the use of back-tick for string, it is very useful if you want to add a variable inside a string or have a multiline string.

2023-10-05 09:02 UTC, pjoshk commented on script.js
> +  const span = document.createElement('span')
inconsistent naming,
task is descriptive, instead of using li
img and span could be descriptive as well

2023-10-05 09:02 UTC, pjoshk commented on script.js
> +    span.innerHTML = '\u00d7'
good candidate for a constant as explained above

2023-10-05 09:02 UTC, pjoshk commented on script.js
> +  }
do "LI" "SPAN" and "IMG" need to be in capitals?

2023-10-05 09:02 UTC, pjoshk commented on script.js
> +  const input = document.createElement('input')
names could be more descriptive

2023-10-05 09:02 UTC, pjoshk commented on script.js
> +    const xInput = previousTaskElement.querySelector('input')
this can be declared outside the if else statement

2023-10-05 09:02 UTC, pjoshk commented on script.js
> +  localStorage.setItem('data', list.innerHTML)
"data" is a good candidate for a constant

2023-10-05 09:02 UTC, pjoshk commented on script.js
> +function addTask () {
"addTask" and "editTask" functions have too many responsibilities, we can separate dom-manipulation and data-manipulation as their own generic api, task for the next PR. I will explain more after the PR is merged (you can resolve this comment after you've read it)

2023-10-08 05:20 UTC, Samaspp commented on script.js
> +  }
yes, tagName property returns tagnames of html elements in capitals

2023-10-08 13:03 UTC, Samaspp commented on script.js
> +    const xInput = previousTaskElement.querySelector('input')
xInput can be defined only if previousTaskElement is not null and has an input element. hence defined inside else.

2023-10-09 11:43 UTC, pjoshk commented on script.js
> +    const xInput = previousTaskElement.querySelector('input')
you can still initialise the variable as undefined and not use it, just change it from const to a let so you can update it when needed.

What you've done is also totally fine. It's just that you have img, span and input defined then you have xImg, xSpan but missing xInput (just aesthetics of the code). For a reviewer they would just know all the variables they are dealing with from the start of the scope.

2023-10-09 12:00 UTC, Samaspp commented on script.js
> +    const xInput = previousTaskElement.querySelector('input')
okay did that, thanks.

2023-10-09 14:14 UTC, pjoshk commented on script.js
> +    const deleteButton = document.createElement('span')
you've already created them before

2023-10-09 14:14 UTC, pjoshk commented on script.js
> +  let xInputFieldForEdit = null
what's the difference between `editIcon` and `xEditIcon`? maybe `newEditIcon` and `taskEditIcon` would be better? same for other variables

deleteBtn is not really a button but a span. Maybe consider changing html to use a `button` instead? Do you know what's the difference between using a span and button elements in html? Consider reading up on semantic html.

`inputFieldForEdit` avoid using prepositions like `for` for naming variables also 4 word name is probably too long. How about `taskInput`?

On line 59. The difference between undefined and null is that, `undefined` was never defined but `null` is that it's empty by intention. (just something to note, no edit needed there)

2023-10-10 11:46 UTC, Samaspp commented on script.js
> +    const deleteButton = document.createElement('span')
I tried removing the extra declaration inside the else statement and it works fine when a task is edited for the first time. but when I edit a task while already editing another task, the edit and delete icons disappear from the first task. the problem is resolved when I declare them separately outside else statement as `previousEditIcon` and `previousDeleteButton`

2023-10-10 15:17 UTC, pjoshk approved these changes

2023-10-10 15:53 UTC, merged